version: '3'
services:
  python-flask-app:
    container_name: flask-app-cont
    build: .
    image: pyflask-app
    ports:
      - 8080:5000
      - 5000:5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 10s

    